# config/params.yml
# users can change parameters according to their problem

# Input
samplesheet: "config/test.csv"
outdir: "results"

#Quast parameters
min_genome_size: 1000000
max_contigs: 500
min_n50: 10000
min_contigs: 1

# Tool toggles — set false to skip a tool
run_amrfinder: true
run_rgi: true
run_abricate: true
run_resfinder: true

# amr options
amrfinder_ident: 0.9
amrfinder_cov: 0.5

#rgi options
rgi_loose: false

#abricate options
abricate_db: "ncbi"      
abricate_minid: 80
abricate_mincov: 80

#resfinder options
resfinder_threshold: 0.9
resfinder_cov: 0.6

