# config/params.yml

# Input
samplesheet: "config/test.csv"
outdir: "results"

# Tool toggles — set false to skip a tool
run_amrfinder: true
run_rgi: true
run_abricate: true
run_resfinder: true

# Tool thresholds
amrfinder_ident: 0.9
amrfinder_cov: 0.5
rgi_loose: false          # true = include loose hits
abricate_db: "ncbi"       # ncbi, card, resfinder, argannot, megares
abricate_minid: 80
abricate_mincov: 80
resfinder_threshold: 0.9
resfinder_cov: 0.6

# QC thresholds
min_genome_size: 1000000   # 1 MB minimum
min_contigs: 1
